// Brownfield adoption: an existing system enters EOS at the delivery gates (P2-4).
//
// The `delivery-only` profile does not gate discovery, requirements, the PRD, UX or architecture:
// the running system is the baseline, documented as it is (bmad-document-project → docs/index.md).
// What must hold is the other half: every change is still a story that is ready (G5), verified (G7)
// and released (G8) — and without a PRD, the stories are the spec the release is aligned with.
//   node --test .github/eos/brownfield.test.mjs
import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { project, write, run, runJson, cleanup, storyFiles, APP_PROJECT, commitAll, writeManifest } from './test-support.mjs';

after(cleanup);

const BROWNFIELD = { ...APP_PROJECT, workflowProfile: 'delivery-only' };
const declared = (dir) => JSON.parse(readFileSync(join(dir, '.eos/project.json'), 'utf8'));
const LOCAL = { GITHUB_ACTIONS: '', GITLAB_CI: '', CI: '' };

test('init --brownfield declares delivery-only on the Standard track, carries it over, and is refused on the Regulated track', () => {
  const dir = project({}, { withHooks: true });
  const listing = run(dir, ['init']);
  assert.match(listing.out, /--brownfield {6}an existing system: document it as it is/);

  const regulated = run(dir, ['init', 'node-service', '--track', 'regulated', '--brownfield', '--write']);
  assert.equal(regulated.code, 1);
  assert.match(regulated.out, /The Regulated track requires the product baseline/);

  const configOnly = runJson(dir, ['init', 'config-only', '--brownfield', '--write']);
  assert.equal(configOnly.code, 0, configOnly.out);
  assert.equal(configOnly.json.brownfield, true);
  assert.equal(declared(dir).workflowProfile, 'delivery-only');
  // Code lands: the pack adds a stack, and the adoption the project chose carries over — like the track.
  const gains = runJson(dir, ['init', 'node-service', '--write']);
  assert.equal(gains.code, 0, gains.out);
  assert.equal(declared(dir).workflowProfile, 'delivery-only');
  assert.deepEqual(declared(dir).stacks, ['node']);
  // Starting over is deliberate, and without --brownfield it is a full baseline again.
  assert.equal(run(dir, ['init', 'node-service', '--force', '--write']).code, 0);
  assert.equal(declared(dir).workflowProfile, 'standard-product');
});

test('next asks for the as-is documentation, then for the first story — never for discovery', () => {
  const dir = project({ '.eos/project.json': BROWNFIELD }, { withHooks: true });
  let next = runJson(dir, ['next']);
  assert.equal(next.json.recommendedAction.id, 'document-existing-system', next.out);
  assert.equal(next.json.recommendedAction.copilotAgent, 'eos-discovery');
  assert.deepEqual(next.json.recommendedAction.skills, ['bmad-document-project']);
  assert.match(next.json.recommendedAction.reason, /the running system is its baseline/);

  write(dir, 'docs/index.md', '# Project documentation\n\nGenerated by bmad-document-project.\n');
  next = runJson(dir, ['next']);
  assert.equal(next.json.recommendedAction.id, 'plan-stories', next.out);
  assert.match(next.json.recommendedAction.reason, /held to the delivery gates \(G5 ready, G7 verified, G8 released\)/);

  // The same repository on the Standard profile starts at the product baseline.
  write(dir, '.eos/project.json', APP_PROJECT);
  assert.equal(runJson(dir, ['next']).json.recommendedAction.id, 'frame-the-problem');
});

test('without a PRD a story is ready on its own criteria, verified as usual, and the release aligns with the stories it ships', () => {
  const files = storyFiles({ '.eos/project.json': { ...BROWNFIELD, commands: { test: 'node --version' } }, 'docs/index.md': '# As-is\n' });
  delete files['docs/prd.md'];
  const dir = project(files, { withHooks: true });

  const ready = runJson(dir, ['check', '--gate', 'story-ready', '--scope', 'STORY-001'], LOCAL);
  assert.equal(ready.json.checks.find((c) => c.id === 'ac-references-resolve').status, 'NOT_APPLICABLE');
  assert.equal(ready.json.status, 'PASS', JSON.stringify(ready.json.checks.filter((c) => c.status !== 'PASS' && c.status !== 'NOT_APPLICABLE')));
  const verified = runJson(dir, ['check', '--gate', 'verified', '--scope', 'STORY-001'], LOCAL);
  assert.equal(verified.json.checks.find((c) => c.id === 'trace-complete').status, 'PASS', verified.out);

  commitAll(dir, 'verified');
  writeManifest(dir, { releaseId: 'R-1' });
  const release = runJson(dir, ['check', '--gate', 'release-ready', '--scope', 'R-1'], LOCAL);
  const align = release.json.checks.find((c) => c.id === 'spec-alignment');
  assert.equal(align.status, 'PASS', align.detail);
  assert.match(JSON.stringify(release.json.commands || release.json), /spec-align\.mjs.*--release.*R-1/);
});

test('moving an existing project onto delivery-only is a policy WEAKENING, and back is not', () => {
  const dir = project({ '.eos/project.json': APP_PROJECT }, { withHooks: true });
  write(dir, '.eos/project.json', BROWNFIELD);
  const weaker = runJson(dir, ['policy', 'diff']);
  const change = weaker.json.changes.find((c) => c.id === 'project:workflowProfile:standard-product->delivery-only');
  assert.ok(change, weaker.out);
  assert.equal(change.kind, 'WEAKENING');
  commitAll(dir, 'adopt at the delivery gates');
  write(dir, '.eos/project.json', APP_PROJECT);
  const back = runJson(dir, ['policy', 'diff']).json.changes.find((c) => c.id === 'project:workflowProfile:delivery-only->standard-product');
  assert.ok(back);
  assert.notEqual(back.kind, 'WEAKENING');
});
